project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  description: "Ecletic explorations of data, process and fixing problems"
  site-url: https://peterharrad.github.io/Contributing-Factors/
  title: "Contributing-Factors"
  comments:
    giscus:
      repo: peterharrad/Contributing-Factors
      category: Comments
      mapping: pathname
      reactions-enabled: true
      theme: preferred_color_scheme
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



