project:
  type: website
  output-dir: docs

execute:
  freeze: auto
  
website:
  description: "Ecletic explorations of data, process and fixing problems"
  site-url: https://harrad.org/
  title: "Contributing-Factors"
  draft-mode: gone
  comments:
    giscus:
      repo: peterharrad/Contributing-Factors
      category: Comments
      mapping: pathname
      reactions-enabled: true
      theme: preferred_color_scheme
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/peterharrad
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



